format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$kubernetes\
$docker_context\
$nodejs\
$golang\
$php\
$line_break\
$character"""

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ](bold red)"

[kubernetes]
format = '[âˆ $context](dimmed cyan) '
disabled = false

[docker_context]
format = '[ğŸ³ $context](blue bold)'
disabled = false

[nodejs]
format = '[â¬¢ $version](bold green) '
disabled = false

[golang]
format = '[ğŸ¹ $version](bold cyan) '
disabled = false

[php]
format = '[ğŸ˜ $version](bold purple) '
disabled = false

[directory]
truncation_length = 3
truncation_symbol = "â€¦/"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "ğŸŒ± "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'